<?php
$title = 'My albums';
$this->headTitle($title);
$this->headScript()->appendFile('lol');
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album', array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album', array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<h2>Test Modules</h2>

<h3>TextStyles</h3>
<?php echo $this->bold('Some bold text!'); ?><br />
<?php echo $this->b('Some bold text (using alias)!'); ?><br />
<?php echo $this->italic('Some italic text!'); ?><br />
<?php echo $this->i('Some italic text (using alias)!'); ?><br />
<?php echo $this->underline('Some underline text!'); ?><br />
<?php echo $this->u('Some underline text (using alias)!'); ?><br />

<h3>EveryPage</h3>
<?php
if (isset($foo))
{
	echo "<p>{$foo}</p>";
}
else
{
	echo "<p>EveryPage did not appear to run...</p>";
	echo "<p>Try adding <span style=\"font-family: monospace;\">'foo' => \$this->everypage()->getFoo()</span> to the ViewModel in the action...</p>";
}
?>

<h3>Eventful Log</h3>
<?php
if (is_array($eventful_log))
{
	echo "<ol>";
	foreach($eventful_log as $event)
	{
		echo "<li>{$event}</li>";
	}
	echo "</ol>";
}
?>